# Generated by Django 5.0 on 2023-12-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exponents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("name_of_company", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("desription", models.CharField(max_length=5000)),
                ("image_of_exp1", models.ImageField(blank=True, upload_to="img/")),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("data_begin", models.DateField()),
                ("data_end", models.DateField()),
                ("image_of_event", models.ImageField(blank=True, upload_to="img/")),
                ("description", models.CharField(max_length=5000)),
                ("my_eve", models.BooleanField()),
                ("exp", models.ManyToManyField(to="website.exponents")),
            ],
        ),
    ]
