# Generated by Django 5.0 on 2023-12-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exponents",
            name="my_exp",
            field=models.BooleanField(default=False),
        ),
    ]
